In [1]:
import numpy as np

In [6]:
org_array = np.array([3,1,5,9])

In [3]:
array_result_1 = np.sort(org_array)
print(array_result_1)
print(org_array)


[1 3 5 9]
[3 1 5 9]


In [4]:
array_result_2 = org_array.sort()
print(array_result_2)
print(org_array)


None
[1 3 5 9]


In [7]:
print(org_array)

array_result_3 = np.argsort(org_array)
print(array_result_3)
print(org_array)

[3 1 5 9]
[1 0 2 3]
[3 1 5 9]


In [8]:
print(org_array.shape)

(4,)


In [10]:
print(org_array.reshape([4,1]))
print(org_array)

[[3]
 [1]
 [5]
 [9]]
[3 1 5 9]
